### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by WRKampi**
@conda-forge-admin, please rerender
@conda-forge-admin, please update for conda-build 3

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by WRKampi** [comment]
@synapticarbors ,
You have helped me to get the feedstock started. Can you also help me with this update? I have no idea why this update does not work. I try to update from v0.3.1 to v0.4.0. The Pypi version has been updated, but this Conda update fails.

**Comment by synapticarbors** [comment]
I'm a little confused why it looks like haven't gotten an PRs from the regrobot when the version updated on pypi. But the feedstock itself looks out-of-date. I'm going to try to rerender it here, and if that doesn't work, I'll try manually.

@conda-forge-admin please rerender

**Comment by WRKampi** [comment]
@synapticarbors ,

The test have now passed. Thank you.
Should I click the button to merge the pull request, or is it better to wait until it is automatically merged?
Should I do anything to update the feedstock for future updates?

**Comment by synapticarbors** [comment]
Ok, that re-render seems to have worked. I'm still not sure why this feedstock hasn't been getting automatic PRs from the regro bot when a new release happens on pypi. Normally you'd get a PR with the version bumped, the hash changed and any other changes that conda-forge recommends. Usually all you have to do then is check dependency versions and make sure the tests pass. Hopefully this will happen for the next release, but if it doesn't we should look into it.

You can merge this PR. It won't be done automatically. Typically PRs won't be.

**Pull request merged**
